# Generated by Django 3.2.10 on 2024-05-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_tags', models.CharField(max_length=150)),
                ('product_category', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('available_quantity', models.IntegerField()),
                ('liscence_of_sale', models.URLField()),
                ('product_image', models.ImageField(upload_to='product_information/product_images')),
            ],
        ),
    ]
