# Generated by Django 3.2.10 on 2024-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_quality_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality_shelf',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
